# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: Default

steps:
- task: octane-start-task@2
  inputs:
    OctaneServiceConnection: 'connectionOctane'
    WorkspaceList: '38001'
    CreatePipelineCheckbox: true
    GithubRepositoryConnection: 
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test -Dcucumber.plugin=pretty'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  continueOnError: true

- script: |
    mvn com.microfocus.adm.almoctane.bdd:bdd2octane:run -Dmaven.test.failure.ignore=true -DreportFiles="**target/surefire-reports/TEST*.xml" -DfeatureFiles="**src/test/resources/features/*.feature" -Dframework="cucumber-jvm" -DresultFile="converted-test-results.xml"
  displayName: 'Convert Test Results'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/converted-test-results.xml'
    artifact: 'bdd2octaneResults'
    publishLocation: 'pipeline'

- task: DownloadPipelineArtifact@2
  inputs:
    artifact: 'bdd2octaneResults'
    path: '$(System.DefaultWorkingDirectory)/results'
- task: octane-end-task@2
  inputs:
    OctaneServiceConnection: 'connectionOctane'
    WorkspaceList: '38001'